### ISSUE TITLE
"Don’t compose without a scale" is malformed in Chrome

### ISSUE THREAD

**Issue by tmcw** [clagnut/webtypography#17]
![2014-06-14 at 7 38 pm](https://cloud.githubusercontent.com/assets/32314/3279817/00470bfc-f41d-11e3-9e05-c394f4d7b737.png)

The curly quote here is not agreeing with Google Chrome 36.0.1985.67 beta. Works in Firefox.

**Comment by mckennapsean** [comment]
Could not reproduce using Chrome 43, so likely not an issue anymore.
