### ISSUE TITLE
Section 2.1.4 - spacing between sentences

### ISSUE THREAD

**Issue by srevenant** [clagnut/webtypography#24]
You make a fairly assertive claim about 16th century typesetting and use that to claim that longer spacing should not be used.  This is a fallacy that has been recently pushed.  This document goes into better detail on why that is a fallacious argument:

http://www.heracliteanriver.com/?p=324

Single space also hinders speed reading, and the case of Dr. Mr. and others.  Ideally there is "additional" space after a sentence period, to facilitate these use cases.  Should it be "two space characters," not necessarily.

But please, reconsider if you should be promoting the fake myth of why two spaces are used.

**Comment by clagnut** [comment]
*I* don't make that claim: Bringhurst makes that claim. The point of the site is to show that Bringhurst's guidelines (whether you agree or disagree with them) can be implemented on the web.
