### ISSUE TITLE
Line-height isn’t unique in this respect.

### ISSUE THREAD

**Issue by infinnie** [clagnut/webtypography#26]
> a unique characteristic of the line-height property: it is the only CSS property for which non-zero numeric values are allowed without units.

The `line-height` property isn’t alone in this respect: `z-index`, `flex-grow`, `flex-shrink` and many other properties all support numeric values without units.

Also, `line-height: 0` is valid in CSS.

**Comment by bakert** [comment]
I fixed this in #29
